<?php get_header();
// echo do_shortcode('[tainacan-search]');

echo '<section class="home-acervo">';
	// echo '<h1 class="max-large margin-one-column">Ilustrações</h1>';
	echo '<div class="wrap">';
		echo '<div class="sub-wrap"><ul>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-4.jpg" alt="">';
				echo '<mark>untemporary</mark>';
				echo '<hgroup><h1>Chi Clayborn</h1>'; 
				echo '<h2>Dewey, broadtail, rotundo</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-2.jpg" alt="">';
				echo '<mark>Characeae</mark>';
				echo '<hgroup><h1>Madaline Tengben</h1>'; 
				echo '<h2>fundal, formative, benignantly</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-3.jpg" alt="">';
				echo '<mark>waywort</mark>';
				echo '<hgroup><h1>Salvatore Stobb</h1>'; 
				echo '<h2>isopterous, plethorical, Grammontine</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-6.jpg" alt="">';
				echo '<mark>necrologue</mark>';
				echo '<hgroup><h1>Joline Kababik</h1>'; 
				echo '<h2>teach, hydrocobalticyanic, checkerwise</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-7.jpg" alt="">';
				echo '<mark>agillawood</mark>';
				echo '<hgroup><h1>Frederick Emel</h1>'; 
				echo '<h2>epitonion, Danite, cwierc</h2></hgroup>';
			echo '</a></li>';
		echo '</ul></div>';
	echo '</div>';
echo '</section>';

echo '<section class="home-acervo">';
	// echo '<h1 class="max-large margin-one-column">Mapas</h1>';
	echo '<div class="wrap">';
		echo '<div class="sub-wrap"><ul>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-1.jpg" alt="">';
				echo '<mark>almost</mark>';
				echo '<hgroup><h1>Chi Clayborn</h1>'; 
				echo '<h2>Dewey, broadtail, rotundo</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-5.jpg" alt="">';
				echo '<mark>Lucanus</mark>';
				echo '<hgroup><h1>Madaline Tengben</h1>'; 
				echo '<h2>fundal, formative, benignantly</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-8.jpg" alt="">';
				echo '<mark>outswarm</mark>';
				echo '<hgroup><h1>Salvatore Stobb</h1>'; 
				echo '<h2>isopterous, plethorical, Grammontine</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-9.jpg" alt="">';
				echo '<mark>cyesis</mark>';
				echo '<hgroup><h1>Joline Kababik</h1>'; 
				echo '<h2>teach, hydrocobalticyanic, checkerwise</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-10.jpg" alt="">';
				echo '<mark>ghaist</mark>';
				echo '<hgroup><h1>Frederick Emel</h1>'; 
				echo '<h2>epitonion, Danite, cwierc</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-8.jpg" alt="">';
				echo '<mark>contradictiously</mark>';
				echo '<hgroup><h1>Salvatore Stobb</h1>'; 
				echo '<h2>isopterous, plethorical, Grammontine</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-9.jpg" alt="">';
				echo '<mark>thoracogastroschisis</mark>';
				echo '<hgroup><h1>Joline Kababik</h1>'; 
				echo '<h2>teach, hydrocobalticyanic, checkerwise</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-10.jpg" alt="">';
				echo '<mark>fluible</mark>';
				echo '<hgroup><h1>Frederick Emel</h1>'; 
				echo '<h2>epitonion, Danite, cwierc</h2></hgroup>';
			echo '</a></li>';
		echo '</ul></div>';
	echo '</div>';
echo '</section>';

echo '<section class="home-acervo">';
	// echo '<h1 class="max-large margin-one-column">Infográficos</h1>';
	echo '<div class="wrap">';
		echo '<div class="sub-wrap"><ul>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-4.jpg" alt="">';
				echo '<mark>tyrosine</mark>';
				echo '<hgroup><h1>Chi Clayborn</h1>'; 
				echo '<h2>Dewey, broadtail, rotundo</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-2.jpg" alt="">';
				echo '<mark>greenling</mark>';
				echo '<hgroup><h1>Madaline Tengben</h1>'; 
				echo '<h2>fundal, formative, benignantly</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-3.jpg" alt="">';
				echo '<mark>Thetis</mark>';
				echo '<hgroup><h1>Salvatore Stobb</h1>'; 
				echo '<h2>isopterous, plethorical, Grammontine</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-6.jpg" alt="">';
				echo '<mark>orchestrion</mark>';
				echo '<hgroup><h1>Joline Kababik</h1>'; 
				echo '<h2>teach, hydrocobalticyanic, checkerwise</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-7.jpg" alt="">';
				echo '<mark>nonepileptic</mark>';
				echo '<hgroup><h1>Frederick Emel</h1>'; 
				echo '<h2>epitonion, Danite, cwierc</h2></hgroup>';
			echo '</a></li>';
		echo '</ul></div>';
	echo '</div>';
echo '</section>';


 get_footer(); ?>
