<?php get_header();
// echo do_shortcode('[tainacan-search]');

echo '<section class="home-acervo">';
	echo '<div class="wrap">';
		echo '<div class="sub-wrap"><ul>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-4.jpg" alt="">';
				echo '<hgroup><h1>Chi Clayborn</h1>'; 
				echo '<h2>Dewey, broadtail, rotundo</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-2.jpg" alt="">';
				echo '<hgroup><h1>Madaline Tengben</h1>'; 
				echo '<h2>fundal, formative, benignantly</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-3.jpg" alt="">';
				echo '<hgroup><h1>Salvatore Stobb</h1>'; 
				echo '<h2>isopterous, plethorical, Grammontine</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-6.jpg" alt="">';
				echo '<hgroup><h1>Joline Kababik</h1>'; 
				echo '<h2>teach, hydrocobalticyanic, checkerwise</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-7.jpg" alt="">';
				echo '<hgroup><h1>Frederick Emel</h1>'; 
				echo '<h2>epitonion, Danite, cwierc</h2></hgroup>';
			echo '</a></li>';
		echo '</ul></div>';
	echo '</div>';
echo '</section>';

echo '<section class="home-acervo">';
	echo '<div class="wrap">';
		echo '<div class="sub-wrap"><ul>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-4.jpg" alt="">';
				echo '<hgroup><h1>Chi Clayborn</h1>'; 
				echo '<h2>Dewey, broadtail, rotundo</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-2.jpg" alt="">';
				echo '<hgroup><h1>Madaline Tengben</h1>'; 
				echo '<h2>fundal, formative, benignantly</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-3.jpg" alt="">';
				echo '<hgroup><h1>Salvatore Stobb</h1>'; 
				echo '<h2>isopterous, plethorical, Grammontine</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-6.jpg" alt="">';
				echo '<hgroup><h1>Joline Kababik</h1>'; 
				echo '<h2>teach, hydrocobalticyanic, checkerwise</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-7.jpg" alt="">';
				echo '<hgroup><h1>Frederick Emel</h1>'; 
				echo '<h2>epitonion, Danite, cwierc</h2></hgroup>';
			echo '</a></li>';
		echo '</ul></div>';
	echo '</div>';
echo '</section>';

echo '<section class="home-acervo">';
	echo '<div class="wrap">';
		echo '<div class="sub-wrap"><ul>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-4.jpg" alt="">';
				echo '<hgroup><h1>Chi Clayborn</h1>'; 
				echo '<h2>Dewey, broadtail, rotundo</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-2.jpg" alt="">';
				echo '<hgroup><h1>Madaline Tengben</h1>'; 
				echo '<h2>fundal, formative, benignantly</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-3.jpg" alt="">';
				echo '<hgroup><h1>Salvatore Stobb</h1>'; 
				echo '<h2>isopterous, plethorical, Grammontine</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-6.jpg" alt="">';
				echo '<hgroup><h1>Joline Kababik</h1>'; 
				echo '<h2>teach, hydrocobalticyanic, checkerwise</h2></hgroup>';
			echo '</a></li>';
			echo '<li><a href="http://acervoimg.local/acervo/fig-3-jpg/">'; 
				echo '<img src="http://acervoimg.local/wp-content/uploads/2019/07/fig-7.jpg" alt="">';
				echo '<hgroup><h1>Frederick Emel</h1>'; 
				echo '<h2>epitonion, Danite, cwierc</h2></hgroup>';
			echo '</a></li>';
		echo '</ul></div>';
	echo '</div>';
echo '</section>';


 get_footer(); ?>
